name: Release
on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: ['18.x']
    runs-on: ${{ matrix.os }}
    steps:
    #
    # Basic Setup
    #
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install Module Dependencies
    #   run: npm clean-install --omit=optional
    - name: Install Dependencies
      run: npm install

    #
    # Package and Upload Extension
    #
    # NOTE:
    # The "vscode:prepublish" script in package.json will be executed to compile the extension
    # prior to packaging.
    #
    - name: Package Extension into .vsix file
      id: asset
      shell: bash
      run: >
        npx vsce package;
        echo ::set-output name=vsix_path::$(ls *.vsix)

    - name: Upload .vsix file to Github as release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.asset.outputs.vsix_path }}
        asset_name: ${{ steps.asset.outputs.vsix_path }}
        asset_content_type: application/zip
